/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermeniSiConditiiRouteImport } from './routes/termeni-si-conditii'
import { Route as SolRouteImport } from './routes/sol'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SchimbMarimeRouteImport } from './routes/schimb-marime'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReturRouteImport } from './routes/retur'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as LivrareRouteImport } from './routes/livrare'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AnpcRouteImport } from './routes/anpc'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopListaRouteImport } from './routes/shop.lista'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniSiConditiiRoute = TermeniSiConditiiRouteImport.update({
  id: '/termeni-si-conditii',
  path: '/termeni-si-conditii',
  getParentRoute: () => rootRouteImport,
} as any)
const SolRoute = SolRouteImport.update({
  id: '/sol',
  path: '/sol',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SchimbMarimeRoute = SchimbMarimeRouteImport.update({
  id: '/schimb-marime',
  path: '/schimb-marime',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturRoute = ReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrareRoute = LivrareRouteImport.update({
  id: '/livrare',
  path: '/livrare',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AnpcRoute = AnpcRouteImport.update({
  id: '/anpc',
  path: '/anpc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopListaRoute = ShopListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => ShopRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/anpc': typeof AnpcRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/delivery': typeof DeliveryRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRoute
  '/livrare': typeof LivrareRoute
  '/lookbook': typeof LookbookRoute
  '/manifest': typeof ManifestRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/retur': typeof ReturRoute
  '/returns': typeof ReturnsRoute
  '/schimb-marime': typeof SchimbMarimeRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/sol': typeof SolRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/lista': typeof ShopListaRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/anpc': typeof AnpcRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/delivery': typeof DeliveryRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRoute
  '/livrare': typeof LivrareRoute
  '/lookbook': typeof LookbookRoute
  '/manifest': typeof ManifestRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/retur': typeof ReturRoute
  '/returns': typeof ReturnsRoute
  '/schimb-marime': typeof SchimbMarimeRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/sol': typeof SolRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/lista': typeof ShopListaRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/anpc': typeof AnpcRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/delivery': typeof DeliveryRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRoute
  '/livrare': typeof LivrareRoute
  '/lookbook': typeof LookbookRoute
  '/manifest': typeof ManifestRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/retur': typeof ReturRoute
  '/returns': typeof ReturnsRoute
  '/schimb-marime': typeof SchimbMarimeRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/sol': typeof SolRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/lista': typeof ShopListaRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/anpc'
    | '/cart'
    | '/collections'
    | '/confidentialitate'
    | '/contact'
    | '/cookies'
    | '/delivery'
    | '/exchange'
    | '/faq'
    | '/journal'
    | '/livrare'
    | '/lookbook'
    | '/manifest'
    | '/mcp'
    | '/privacy'
    | '/retur'
    | '/returns'
    | '/schimb-marime'
    | '/shop'
    | '/size-guide'
    | '/sol'
    | '/termeni-si-conditii'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$handle'
    | '/shop/lista'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/anpc'
    | '/cart'
    | '/collections'
    | '/confidentialitate'
    | '/contact'
    | '/cookies'
    | '/delivery'
    | '/exchange'
    | '/faq'
    | '/journal'
    | '/livrare'
    | '/lookbook'
    | '/manifest'
    | '/mcp'
    | '/privacy'
    | '/retur'
    | '/returns'
    | '/schimb-marime'
    | '/shop'
    | '/size-guide'
    | '/sol'
    | '/termeni-si-conditii'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$handle'
    | '/shop/lista'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/anpc'
    | '/cart'
    | '/collections'
    | '/confidentialitate'
    | '/contact'
    | '/cookies'
    | '/delivery'
    | '/exchange'
    | '/faq'
    | '/journal'
    | '/livrare'
    | '/lookbook'
    | '/manifest'
    | '/mcp'
    | '/privacy'
    | '/retur'
    | '/returns'
    | '/schimb-marime'
    | '/shop'
    | '/size-guide'
    | '/sol'
    | '/termeni-si-conditii'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$handle'
    | '/shop/lista'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AnpcRoute: typeof AnpcRoute
  CartRoute: typeof CartRoute
  CollectionsRoute: typeof CollectionsRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DeliveryRoute: typeof DeliveryRoute
  ExchangeRoute: typeof ExchangeRoute
  FaqRoute: typeof FaqRoute
  JournalRoute: typeof JournalRoute
  LivrareRoute: typeof LivrareRoute
  LookbookRoute: typeof LookbookRoute
  ManifestRoute: typeof ManifestRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturRoute: typeof ReturRoute
  ReturnsRoute: typeof ReturnsRoute
  SchimbMarimeRoute: typeof SchimbMarimeRoute
  ShopRoute: typeof ShopRouteWithChildren
  SizeGuideRoute: typeof SizeGuideRoute
  SolRoute: typeof SolRoute
  TermeniSiConditiiRoute: typeof TermeniSiConditiiRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProductHandleRoute: typeof ProductHandleRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni-si-conditii': {
      id: '/termeni-si-conditii'
      path: '/termeni-si-conditii'
      fullPath: '/termeni-si-conditii'
      preLoaderRoute: typeof TermeniSiConditiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol': {
      id: '/sol'
      path: '/sol'
      fullPath: '/sol'
      preLoaderRoute: typeof SolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schimb-marime': {
      id: '/schimb-marime'
      path: '/schimb-marime'
      fullPath: '/schimb-marime'
      preLoaderRoute: typeof SchimbMarimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retur': {
      id: '/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livrare': {
      id: '/livrare'
      path: '/livrare'
      fullPath: '/livrare'
      preLoaderRoute: typeof LivrareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anpc': {
      id: '/anpc'
      path: '/anpc'
      fullPath: '/anpc'
      preLoaderRoute: typeof AnpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/lista': {
      id: '/shop/lista'
      path: '/lista'
      fullPath: '/shop/lista'
      preLoaderRoute: typeof ShopListaRouteImport
      parentRoute: typeof ShopRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopListaRoute: typeof ShopListaRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopListaRoute: ShopListaRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AnpcRoute: AnpcRoute,
  CartRoute: CartRoute,
  CollectionsRoute: CollectionsRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DeliveryRoute: DeliveryRoute,
  ExchangeRoute: ExchangeRoute,
  FaqRoute: FaqRoute,
  JournalRoute: JournalRoute,
  LivrareRoute: LivrareRoute,
  LookbookRoute: LookbookRoute,
  ManifestRoute: ManifestRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ReturRoute: ReturRoute,
  ReturnsRoute: ReturnsRoute,
  SchimbMarimeRoute: SchimbMarimeRoute,
  ShopRoute: ShopRouteWithChildren,
  SizeGuideRoute: SizeGuideRoute,
  SolRoute: SolRoute,
  TermeniSiConditiiRoute: TermeniSiConditiiRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProductHandleRoute: ProductHandleRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
